.travis.yml
build.sbt
src/main/scala/edu/eckerd/alterpass/ldap/LdapAdmin.scala

No tests, most basic sketch of an LDAP module

Add Ldap Elements For Bind and Change Password

---

src/main/resources/pages/changepw.html
src/main/resources/pages/recovery.html

Now if you submit successfully it will clear the fields.

Made it clear the forms upon successful submit

---

src/main/resources/pages/changepw.html
src/main/resources/pages/recovery.html

Added both real-time and submit button validation for the strength and length of the two passwords, according to the guidelines on the page.

Added front-end strength and length validation

---

src/main/resources/pages/forgotpw.html

Can't really test locally because of the way this API is set up, so apologies for all of the PR's

Fix stupid apostrophes messing up the jQuery calls

---

src/main/resources/pages/forgotpw.html

handle 400 for bad username/trying to reset too soon; 200 for success

Handle different HTTP status codes.

---

src/main/resources/pages/changepw.html

Better status code handling for changepw app, reporting to user if there was a bad user/password combination for old credentials.

Added status code handling to front end for changepw

---

src/main/resources/pages/recovery.html

For the recovery page, return an error if the user gave a bad username.  Otherwise, confirm successfully changed password

Status code handling for the password recovery page

---

src/main/resources/pages/recovery.html

Recovery page wasn't displaying the right message due to wrong http status code. Fixed

Change 200 success to 201 created

---

src/main/resources/static/css/changepass.css

This should style changepw page properly

Forgot CSS for changepw page

---

src/main/scala/edu/eckerd/alterpass/http/StaticSite.scala

Not sure how those spaces got in there.

Fix spaces

---

.gitignore
src/main/resources/logback.xml
src/main/scala/edu/eckerd/alterpass/AlterPassServer.scala
src/main/scala/edu/eckerd/alterpass/Configuration.scala
src/main/scala/edu/eckerd/alterpass/database/SqlLiteDB.scala
src/main/scala/edu/eckerd/alterpass/email/Emailer.scala
src/main/scala/edu/eckerd/alterpass/http/ChangePassword.scala
src/main/scala/edu/eckerd/alterpass/http/ForgotPassword.scala

Email now has independent variable for link seperate from that for the server. Adding Logging to File for Server for easy lookup.
Introduces new environmental variable `EMAIL_LINK` which will need to be present.

Updated Logging and Config for Email

---

src/main/scala/edu/eckerd/alterpass/agingfile/AgingFile.scala

Uncertain about this one. :fire:

AgingFile Changed ; to :

---

src/main/resources/pages/changepw.html
src/main/resources/pages/forgotpw.html
src/main/resources/pages/recovery.html
src/main/resources/static/css/alterpass.css
src/main/resources/static/css/bootstrap.css
src/main/resources/static/css/changepass.css
src/main/resources/static/css/recovery.css

Made a bunch of design changes to the HTML and CSS, including a new responsive footer, color/font changes, positioning and layout, etc.  The idea is to use these changes as a 'precedent' for a stylesheet going forward for other pages.  I did have to modify Bootstrap to fit some of the changes.

Made major design changes to match our new standards going forward.

---

src/main/resources/pages/changepw.html
src/main/resources/pages/forgotpw.html
src/main/resources/pages/recovery.html

Moved the message div's outside of the form so that upon a successful submission Ajax will clear the form out.  That way the user gets some kind of 'feedback' that it was successful and doesn't accidentally change their password twice, etc.

Added form-clearing functionality after a successful submission.

---

build.sbt
src/main/scala/edu/eckerd/alterpass/AlterPassServer.scala
src/main/scala/edu/eckerd/alterpass/database/SqlLiteDB.scala
src/main/scala/edu/eckerd/alterpass/http/ChangePassword.scala
src/main/scala/edu/eckerd/alterpass/http/ForgotPassword.scala
src/main/scala/edu/eckerd/alterpass/http/StaticSite.scala

Updated to http4s 0.17.0-RC1, and doobie 0.4.2 now on stable versions. Revert to snapshot version

Update Http4s and Doobie

---

src/main/resources/pages/changepw.html

Alumni should be resetting their passwords using Google, so I added this info to the change password page.

Added info for alumin using the app

---

src/main/scala/edu/eckerd/alterpass/database/OracleDB.scala
src/main/scala/edu/eckerd/alterpass/database/SqlLiteDB.scala
src/main/scala/edu/eckerd/alterpass/http/ForgotPassword.scala

Quick initial sketch of fix for ECA.

Change ECA Handling

---

src/main/resources/pages/changepw.html
src/main/scala/edu/eckerd/alterpass/database/OracleDB.scala
src/main/scala/edu/eckerd/alterpass/database/SqlLiteDB.scala
src/main/scala/edu/eckerd/alterpass/http/ForgotPassword.scala

This has the ECA handling changes, they were already merged into Test, where I hope they were tested.
Hopefully we can merge these soon.

Merge Test Changes to Master

---

.travis.yml
build.sbt
project/build.properties
project/plugins.sbt
src/main/scala/edu/eckerd/alterpass/AlterPassServer.scala
src/main/scala/edu/eckerd/alterpass/Configuration.scala
src/main/scala/edu/eckerd/alterpass/agingfile/AgingFile.scala
src/main/scala/edu/eckerd/alterpass/database/OracleDB.scala
src/main/scala/edu/eckerd/alterpass/database/SqlLiteDB.scala
src/main/scala/edu/eckerd/alterpass/email/Emailer.scala
src/main/scala/edu/eckerd/alterpass/google/GoogleAPI.scala
src/main/scala/edu/eckerd/alterpass/http/ChangePassword.scala
src/main/scala/edu/eckerd/alterpass/http/ForgotPassword.scala
src/main/scala/edu/eckerd/alterpass/http/StaticSite.scala
src/main/scala/edu/eckerd/alterpass/ldap/Ldap.scala
src/main/scala/edu/eckerd/alterpass/ldap/LdapAdmin.scala
src/main/scala/edu/eckerd/alterpass/models/ForgotPasswordReturn.scala
src/main/scala/edu/eckerd/alterpass/models/Toolbox.scala

Http4s, Circe, Doobie which transitively upgrades Cats and Cats-Effect

Upgrade Dependency Chain

---

src/main/scala/edu/eckerd/alterpass/database/OracleDB.scala

Add a comma to fix off-by-one error; otherwise forgotPW will return a 500

Fix SQL Syntax

---

src/main/scala/edu/eckerd/alterpass/database/SqlLiteDB.scala

Remove comma to fix SQL error or missing database (near "FROM": syntax error)

Fix SQL query

---

src/main/resources/pages/forgotpw.html
src/main/resources/static/css/alterpass.css

Forgive me for merging my own PR.

Fix overlapping footer on forgot page

---

src/main/resources/pages/changepw.html
src/main/resources/pages/forgotpw.html

Clean up a lot of the JS and add case sanitization to the forgot password change so it doesn't matter if someone types in cEleBiKw when they're entering username.

Add lower case sanitization for forgot page
